import type { Metadata } from 'next'
import './globals.css'
import { Kanit } from 'next/font/google'
import { Provider } from '.'

export const metadata: Metadata = {
  title: 'Pancake Swap',
  description: 'Generated by create next app',
}

const kanit = Kanit({subsets : ['latin'], weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"]})

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
})
 {
  return (
    <html lang="en" >
      <body className={kanit.className}>
      <Provider>
        {children}
      </Provider>
      </body>
    </html>
  )
}
